-- =============================================================================
-- Office Department Module: employees + attendance (check-in/out) + QR sessions + logs
-- Safe to run multiple times (IF NOT EXISTS used where possible).
-- =============================================================================

-- -----------------------------
-- 1) Office employees
-- -----------------------------
CREATE TABLE IF NOT EXISTS public.office_employees (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  employee_code text NOT NULL UNIQUE,
  name text NOT NULL,
  -- Required: we bind office data access to the logged-in user's email.
  email text NOT NULL UNIQUE,
  phone text,
  department text NOT NULL DEFAULT 'Office',
  device_id text,
  dynamic_link_token text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_office_employees_department ON public.office_employees(department);
CREATE INDEX IF NOT EXISTS idx_office_employees_employee_code ON public.office_employees(employee_code);

-- -----------------------------
-- 2) Office attendance (one row per employee per date)
-- -----------------------------
CREATE TABLE IF NOT EXISTS public.office_attendance (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL REFERENCES public.office_employees(id) ON DELETE CASCADE,
  date date NOT NULL,
  check_in timestamptz,
  check_out timestamptz,
  worked_hours numeric,
  method text NOT NULL DEFAULT 'biometric' CHECK (method IN ('biometric', 'qr', 'manual')),
  location text,
  device text,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT office_attendance_unique_employee_date UNIQUE (employee_id, date),
  CONSTRAINT office_attendance_check_order CHECK (
    check_in IS NULL OR check_out IS NULL OR check_out >= check_in
  )
);

CREATE INDEX IF NOT EXISTS idx_office_attendance_employee_date ON public.office_attendance(employee_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_office_attendance_date ON public.office_attendance(date DESC);
CREATE INDEX IF NOT EXISTS idx_office_attendance_method ON public.office_attendance(method);

-- Auto-calc worked_hours whenever check_in/check_out change.
CREATE OR REPLACE FUNCTION public.office_compute_worked_hours()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.check_in IS NOT NULL AND NEW.check_out IS NOT NULL THEN
    -- Hours as a decimal. Example: 8.25 = 8h 15m
    NEW.worked_hours := ROUND(EXTRACT(EPOCH FROM (NEW.check_out - NEW.check_in)) / 3600.0, 2);
  ELSE
    NEW.worked_hours := NULL;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_office_compute_worked_hours ON public.office_attendance;
CREATE TRIGGER trg_office_compute_worked_hours
BEFORE INSERT OR UPDATE OF check_in, check_out
ON public.office_attendance
FOR EACH ROW
EXECUTE FUNCTION public.office_compute_worked_hours();

-- -----------------------------
-- 3) QR sessions (generated by admin/HR)
-- -----------------------------
CREATE TABLE IF NOT EXISTS public.office_qr_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  site text NOT NULL,
  shift text,
  token text NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_office_qr_sessions_expires_at ON public.office_qr_sessions(expires_at);
CREATE INDEX IF NOT EXISTS idx_office_qr_sessions_site ON public.office_qr_sessions(site);

-- -----------------------------
-- 4) Attendance logs (audit trail)
-- -----------------------------
CREATE TABLE IF NOT EXISTS public.office_attendance_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL REFERENCES public.office_employees(id) ON DELETE CASCADE,
  action text NOT NULL CHECK (action IN ('checkin', 'checkout')),
  method text NOT NULL CHECK (method IN ('qr', 'biometric', 'manual')),
  timestamp timestamptz NOT NULL,
  ip_address inet,
  device_info text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT office_attendance_logs_dedupe UNIQUE (employee_id, action, method, timestamp)
);

CREATE INDEX IF NOT EXISTS idx_office_attendance_logs_employee_time ON public.office_attendance_logs(employee_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_office_attendance_logs_timestamp ON public.office_attendance_logs(timestamp DESC);

-- -----------------------------
-- 5) RLS (recommended). Service-role server routes bypass this.
-- -----------------------------
ALTER TABLE public.office_employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.office_attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.office_qr_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.office_attendance_logs ENABLE ROW LEVEL SECURITY;

-- Employees can view only their own office employee row (by email).
DROP POLICY IF EXISTS "office_employees_select_own" ON public.office_employees;
CREATE POLICY "office_employees_select_own"
ON public.office_employees
FOR SELECT
TO authenticated
USING (email IS NOT NULL AND (auth.jwt() ->> 'email') = email);

-- Employees can view only their own attendance + logs (by joining to office_employees via email).
DROP POLICY IF EXISTS "office_attendance_select_own" ON public.office_attendance;
CREATE POLICY "office_attendance_select_own"
ON public.office_attendance
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.office_employees e
    WHERE e.id = office_attendance.employee_id
      AND e.email IS NOT NULL
      AND (auth.jwt() ->> 'email') = e.email
  )
);

DROP POLICY IF EXISTS "office_attendance_logs_select_own" ON public.office_attendance_logs;
CREATE POLICY "office_attendance_logs_select_own"
ON public.office_attendance_logs
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.office_employees e
    WHERE e.id = office_attendance_logs.employee_id
      AND e.email IS NOT NULL
      AND (auth.jwt() ->> 'email') = e.email
  )
);

-- QR sessions are admin-only (no direct employee access). Keep locked down by default.
-- Admin/server routes will use service role. If you later want admin users (role=admin) to use anon client,
-- we can add a policy tied to profiles.role.

